# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'window.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(786, 618)
        self.MplWidget = MplWidget(Form)
        self.MplWidget.setEnabled(True)
        self.MplWidget.setGeometry(QtCore.QRect(380, 20, 401, 381))
        self.MplWidget.setObjectName("MplWidget")
        self.groupBoxSimu = QtWidgets.QGroupBox(Form)
        self.groupBoxSimu.setEnabled(True)
        self.groupBoxSimu.setGeometry(QtCore.QRect(50, 90, 191, 121))
        self.groupBoxSimu.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBoxSimu.setObjectName("groupBoxSimu")
        self.buttonTest = QtWidgets.QPushButton(self.groupBoxSimu)
        self.buttonTest.setGeometry(QtCore.QRect(50, 50, 71, 25))
        font = QtGui.QFont()
        font.setFamily("Noto Sans Newa")
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.buttonTest.setFont(font)
        self.buttonTest.setAutoFillBackground(False)
        self.buttonTest.setStyleSheet("background-color: rgb(245, 194, 17);")
        self.buttonTest.setObjectName("buttonTest")
        self.buttonChooseTest = QtWidgets.QPushButton(Form)
        self.buttonChooseTest.setGeometry(QtCore.QRect(450, 220, 131, 25))
        font = QtGui.QFont()
        font.setFamily("Noto Sans Newa")
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.buttonChooseTest.setFont(font)
        self.buttonChooseTest.setAutoFillBackground(False)
        self.buttonChooseTest.setStyleSheet("background-color: rgb(245, 194, 17);")
        self.buttonChooseTest.setObjectName("buttonChooseTest")
        self.buttonChooseStart = QtWidgets.QPushButton(Form)
        self.buttonChooseStart.setGeometry(QtCore.QRect(160, 220, 131, 25))
        font = QtGui.QFont()
        font.setFamily("Noto Sans Newa")
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.buttonChooseStart.setFont(font)
        self.buttonChooseStart.setAutoFillBackground(False)
        self.buttonChooseStart.setStyleSheet("\n"
"background-color: rgb(38, 162, 105);")
        self.buttonChooseStart.setObjectName("buttonChooseStart")
        self.logList = QtWidgets.QListView(Form)
        self.logList.setGeometry(QtCore.QRect(10, 270, 361, 192))
        self.logList.setObjectName("logList")
        self.simStateText = QtWidgets.QPlainTextEdit(Form)
        self.simStateText.setGeometry(QtCore.QRect(120, 510, 104, 70))
        self.simStateText.setObjectName("simStateText")
        self.simDetectionText = QtWidgets.QPlainTextEdit(Form)
        self.simDetectionText.setGeometry(QtCore.QRect(440, 490, 104, 70))
        self.simDetectionText.setObjectName("simDetectionText")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(Form)
        self.plainTextEdit.setGeometry(QtCore.QRect(110, 480, 151, 31))
        self.plainTextEdit.setStyleSheet("background-color: rgba(191, 64, 64, 0);")
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.plainTextEdit_2 = QtWidgets.QPlainTextEdit(Form)
        self.plainTextEdit_2.setGeometry(QtCore.QRect(430, 460, 151, 31))
        self.plainTextEdit_2.setStyleSheet("background-color: rgba(191, 64, 64, 0);")
        self.plainTextEdit_2.setObjectName("plainTextEdit_2")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.groupBoxSimu.setTitle(_translate("Form", "Simulatiemodus"))
        self.buttonTest.setText(_translate("Form", "Test"))
        self.buttonChooseTest.setText(_translate("Form", "Simulatiemodus"))
        self.buttonChooseStart.setText(_translate("Form", "Start"))
        self.plainTextEdit.setPlainText(_translate("Form", "Current real state:"))
        self.plainTextEdit_2.setPlainText(_translate("Form", "Detected State:"))
from .mplwidget import MplWidget
